apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - patch: |-
      - op: add
        path: "/spec/env/-"
        value:
          name: ENVIRONMENT
          value: beta
    target:
      kind: Application
      name: fint-kontroll-user-pod