
on:
  push:
    branches: ['main']

#  workflow_dispatch:

name: Podlet build and deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ALPHA_CLUSTER_NAME: aks-alpha-fint-2021-11-18
  ALPHA_CLUSTER_RESOURCE_GROUP: rg-aks-alpha
  BETA_CLUSTER_NAME: aks-beta-fint-2021-11-23
  BETA_CLUSTER_RESOURCE_GROUP: rg-aks-beta
  API_CLUSTER_NAME: aks-api-fint-2022-02-08
  API_CLUSTER_RESOURCE_GROUP: rg-aks-api


jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Build React App
        run: yarn build

      - name: Copy asset-manifest.json to podlet
        run: cp build/asset-manifest.json podlet/

      - name: Rename main.*.js file
        run: mv build/static/js/main.*.js build/static/js/main.js
      - name: Rename main.*.css file
        run: mv build/static/css/main.*.css build/static/css/main.css

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CLI_CDN }}

      - name: Upload assets to CDN
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az storage blob upload \
              --file "build/static/js/main.js" \
              --container-name "alpha/${{ github.event.repository.name }}" \
              --account-name stflaiscdn \
              --name main.js \
              --overwrite
            az storage blob upload \
              --file "build/static/css/main.css" \
              --container-name "alpha/${{ github.event.repository.name }}" \
              --account-name stflaiscdn \
              --name main.css \
              --overwrite

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      ## Alpha cluster ##
      - name: Bake alpha manifests with Kustomize
        uses: azure/k8s-bake@v2.2
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/overlays/alpha'
        id: bake-alpha

      - name: Set the target Alpha cluster.
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AKS_ALPHA_FINT_GITHUB }}'
          cluster-name: ${{ env.ALPHA_CLUSTER_NAME }}
          resource-group: ${{ env.ALPHA_CLUSTER_RESOURCE_GROUP }}

      - name: Deploy to Alpha
        uses: azure/k8s-deploy@v4.4
        with:
          manifests: ${{ steps.bake-alpha.outputs.manifestsBundle }}
          images: |
            ${{ steps.meta.outputs.tags }}
          namespace: fintlabs-no
          action: deploy